/*
 * Titan API
 *
 * API used by the Titan CLI
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package titanclient
// VolumeStatus struct for VolumeStatus
type VolumeStatus struct {
	// Volume name
	Name string `json:"name"`
	// Logical size consumed by the volume
	LogicalSize int64 `json:"logicalSize"`
	// Actual (compressed) size used by the volume
	ActualSize int64 `json:"actualSize"`
	// Client-specific properties
	Properties map[string]interface{} `json:"properties"`
	// True if the volume is ready for use in a runtime environmemnt
	Ready bool `json:"ready"`
	// Optional error message if volume asynchronously failed to be created
	Error string `json:"error,omitempty"`
}
