/*
 * Titan API
 *
 * API used by the Titan CLI
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package titan-client
// Commit struct for Commit
type Commit struct {
	// Commit identifier
	Id string `json:"id"`
	// Additional commit metadata
	Properties map[string]interface{} `json:"properties"`
}
