/*
 * Titan API
 *
 * API used by the Titan CLI
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package titan-client
// Repository struct for Repository
type Repository struct {
	// Repository name
	Name string `json:"name"`
	// Client-specific propertiers
	Properties map[string]interface{} `json:"properties,omitempty"`
}
