/*
 * Titan API
 *
 * API used by the Titan CLI
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package titan-client
// RemoteParameters struct for RemoteParameters
type RemoteParameters struct {
	// Remote type
	Provider string `json:"provider"`
	// Provider-specific remote properties
	Properties map[string]interface{} `json:"properties,omitempty"`
}
