/*
 * Titan API
 *
 * API used by the Titan CLI
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package titan-client
// Context struct for Context
type Context struct {
	// Provider type
	Provider string `json:"provider"`
	// Additional provider-specific configuration
	Properties map[string]interface{} `json:"properties"`
}
